#!/bin/bash
set -e
if [ "$EUID" -ne 0 ]
  then echo "Got to run as root"
  exit 1
fi
cd $(dirname $0)

ABSOLUTE_PATH=$(cd `dirname "${BASH_SOURCE[0]}"` && pwd)'/'
if [ -z "$IPTABLES" ]; then
  #stop firewall
  bash $ABSOLUTE_PATH/firewall-stop

  #run for ip6tables
  echo "Starting ipv6 firewall..."
  export IPTABLES=$(which ip6tables)
  bash $ABSOLUTE_PATH/firewall-start

  #run for iptables
  echo "Starting ipv4 firewall..."
  IPV4=true
  IPTABLES=$(which iptables)
fi

# Create new chains
$IPTABLES -t mangle -N rfw-mangle-postrouting
$IPTABLES -t mangle --insert POSTROUTING -j rfw-mangle-postrouting
$IPTABLES -t nat -N rfw-nat-prerouting
$IPTABLES -t nat --insert PREROUTING -j rfw-nat-prerouting
$IPTABLES -t nat -N rfw-nat-postrouting
$IPTABLES -t nat --insert POSTROUTING -j rfw-nat-postrouting
$IPTABLES -t filter -N rfw-filter-input
$IPTABLES -t filter --insert INPUT -j rfw-filter-input
$IPTABLES -t filter -N rfw-filter-forward
$IPTABLES -t filter --insert FORWARD -j rfw-filter-forward

#Allow LXC containers to use this box for DNS / DHCP (LXC compat)
$IPTABLES -t filter -A rfw-filter-input -p udp --dport 53 -i lxcbr0 -j ACCEPT
$IPTABLES -t filter -A rfw-filter-input -p udp --dport 67 -i lxcbr0 -j ACCEPT
#Some bullshit to fix DHCP bug
$IPTABLES -t mangle -A rfw-mangle-postrouting -o lxcbr0 -p udp -m udp --dport 68 -j CHECKSUM --checksum-fill

magic_func() {
  DTYPE=$1
  DSPEC=$2
  if [ "$DTYPE" == 'lxc' ]; then
    IFACE='lxcbr0'
    if [ "$IPV4" == 'true' ]; then
      IP=$(lxc-info -n $DSPEC -iH | grep -v : | head -1 || true)
    else
      IP=$(lxc-info -n $DSPEC -iH | grep : | head -1 || true)
    fi
  elif [ "$DTYPE" == 'docker'  ]; then
    IFACE='docker0'
    if [ "$IPV4" == 'true' ]; then
      IP=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' $DSPEC || true)
    else
      IP=$(docker inspect --format '{{ .NetworkSettings.GlobalIPv6Address }}' $DSPEC || true)
    fi
  else
    IFACE=$DTYPE
    IP=$DSPEC
    if grep ':' <<< "$IP" > /dev/null; then   # IPv6
      [ "$IPV4" == 'true' ] && return 0 || true
    else
      [ "$IPV4" == 'true' ] || return 0 || true
    fi
  fi

  # Return nothing if there is no IP (e.g. no IPv6 for container)
  if [ -n "$IP" ]; then
    echo "$IP" "$IFACE"
  fi
}


OLDIFS=$IFS;
IFS=$'\n';
for ROW in $(grep -v '^\s*#' forward.config); do
  IFS=$OLDIFS

  ROW=$(echo "$ROW" | tr -d '\n')
  [ -z "$ROW" ] && continue || true

  COL=( $ROW )

  PROTO=${COL[0]}
  PORT=${COL[1]}
  DTYPE=${COL[2]}
  DSPEC=${COL[3]}
  DPORT=${COL[4]}

  PARTS=$(magic_func $DTYPE $DSPEC)
  [ -z "$PARTS" ] && continue || true  # skip anything that doesn't apply
  COL=( $PARTS )
  IP=${COL[0]}
  DIFACE=${COL[1]}
  
  # Actual iptables rules
  $IPTABLES -t nat -A rfw-nat-prerouting --protocol $PROTO --dport $PORT -j DNAT --to-destination $IP:$DPORT
  $IPTABLES -t filter -A rfw-filter-forward --protocol $PROTO --dport $DPORT --destination $IP -j ACCEPT

  # Perform NAT for a container/whatever (-i $DIFACE on NAT might not work)
  $IPTABLES -t nat -A rfw-nat-postrouting -j MASQUERADE --source $IP
  $IPTABLES -t filter -A rfw-filter-forward -o $DIFACE --destination $IP -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
  $IPTABLES -t filter -A rfw-filter-forward -i $DIFACE --source $IP -j ACCEPT

  IFS=$'\n';
done
IFS=$OLDIFS

echo "It definitely worked."

# protocol  port  dtype       dspec         dport
# tcp       8080  docker      grafana       80
# tcp       3192  lxc         blah          22
# tcp       1234  eth0        10.0.3.1      123
