#!/bin/bash
set -e

if [ "$EUID" -ne 0 ]
  then echo "Got to run as root"
  exit 1
fi

ABSOLUTE_PATH=$(cd `dirname "${BASH_SOURCE[0]}"` && pwd)'/'
if [ -z "$IPTABLES" ]; then
  #run for ip6tables
  echo "Stopping ipv6 firewall..."
  export IPTABLES=$(which ip6tables)
  bash $ABSOLUTE_PATH/firewall-stop

  #run for iptables
  echo "Stopping ipv4 firewall..."
  IPV4=true
  IPTABLES=$(which iptables)
fi

delete_chain() {
  CHAIN="$1"

  # Split input chain into three parts
  IFS='-' read -r rfw table base_chain <<< "$CHAIN"

  # base_chain should always be upper case
  base_chain=$(tr '[:lower:]' '[:upper:]' <<<"$base_chain")

  # Delete the jump rule in the main chain that points to this chain
  $IPTABLES -t $table --delete $base_chain -j $CHAIN >/dev/null 2>&1 || true

  # Delete all rules in this chain
  $IPTABLES -t $table --flush $CHAIN >/dev/null 2>&1 || true

  # Delete this chain
  $IPTABLES -t $table --delete-chain $CHAIN >/dev/null 2>&1 || true 
}

# Clean up all of our chains
delete_chain rfw-mangle-postrouting
delete_chain rfw-nat-prerouting
delete_chain rfw-nat-postrouting
delete_chain rfw-filter-input
delete_chain rfw-filter-forward
